services:
  - type: web
    name: task-lottery
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 10000
    disk:
      - name: data_disk
        mountPath: /opt/render/project/src/data
